import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  // ==========================================
  // NAVIGATION
  // ==========================================
  "nav.home": { en: "Home", tr: "Ana Sayfa" },
  "nav.intern": { en: "Intern", tr: "Staj" },
  "nav.jobs": { en: "Jobs", tr: "İşler" },
  "nav.market": { en: "Market", tr: "Pazar" },
  "nav.local": { en: "Local", tr: "Yerel" },
  "nav.login": { en: "Login", tr: "Giriş" },
  "nav.joinNow": { en: "Join Now", tr: "Katıl" },
  "nav.logout": { en: "Logout", tr: "Çıkış" },

  // ==========================================
  // LOGIN PAGE
  // ==========================================
  "login.welcome": { en: "Welcome", tr: "Hoş Geldin" },
  "login.back": { en: "Back", tr: "Tekrar" },
  "login.subtitle": { en: "Log in to your intelligent life assistant.", tr: "Akıllı yaşam asistanınıza giriş yapın." },
  "login.orEmail": { en: "or securely with email", tr: "veya e-posta ile güvenli giriş" },
  "login.emailLabel": { en: "Email Address", tr: "E-posta Adresi" },
  "login.passwordLabel": { en: "Password", tr: "Şifre" },
  "login.forgot": { en: "Forgot?", tr: "Unuttum?" },
  "login.signIn": { en: "Sign In", tr: "Giriş Yap" },
  "login.noAccount": { en: "Don't have an account?", tr: "Hesabınız yok mu?" },
  "login.getStarted": { en: "Get Started for Free", tr: "Ücretsiz Başla" },
  "login.welcomeBack": { en: "Welcome back", tr: "Tekrar hoş geldiniz" },
  "login.setupProfile": { en: "Let's finish setting up your profile first! 🚀", tr: "Önce profilinizi tamamlayalım! 🚀" },
  "login.invalid": { en: "Invalid credentials.", tr: "Geçersiz kimlik bilgileri." },
  "login.googleFail": { en: "Google Login Failed.", tr: "Google girişi başarısız." },
  "login.heroBadge": { en: "Career cockpit", tr: "Kariyer kontrol merkezi" },
  "login.heroPointOne": { en: "Track internships, jobs, and local opportunities in one place.", tr: "Stajlari, isleri ve yerel firsatlari tek yerde takip edin." },
  "login.heroPointTwo": { en: "Continue from your saved progress across every screen.", tr: "Kayitli ilerlemenizle her ekranda kaldiginiz yerden devam edin." },
  "login.heroPointThree": { en: "Use Google or email sign-in with the same profile flow.", tr: "Google veya e-posta ile ayni profil akisini kullanin." },
  "login.metricOne": { en: "ready access", tr: "hazir erisim" },
  "login.metricTwo": { en: "driven workflow", tr: "destekli akış" },
  "login.panelTitle": { en: "Sign in to your workspace", tr: "Calisma alaniniza giris yapin" },
  "login.panelSubtitle": { en: "Pick up your roadmap, saved jobs, and active missions where you left them.", tr: "Yol haritanizi, kayitli islerinizi ve aktif gorevlerinizi kaldiginiz yerden acin." },
  "login.secureLabel": { en: "Encrypted access", tr: "Sifreli erisim" },
  "login.googleUnavailable": { en: "Google login is not configured yet.", tr: "Google girisi henuz yapilandirilmadi." },
  "todo.title": { en: "MISSION CONTROL", tr: "GÖREV KONTROLÜ" },
  "todo.active": { en: "ACTIVE", tr: "AKTİF" },
  "todo.placeholder": { en: "Initialize new objective...", tr: "Yeni hedef başlat..." },
  "todo.launch": { en: "LAUNCH", tr: "BAŞLAT" },
  "todo.critical": { en: "CRITICAL OBJECTIVES", tr: "KRİTİK HEDEFLER" },
  "todo.ongoing": { en: "ONGOING INTERNSHIPS", tr: "DEVAM EDEN STAJLAR" },
  "todo.daily": { en: "DAILY MISSIONS", tr: "GÜNLÜK GÖREVLER" },
  "todo.resolved": { en: "RESOLVED", tr: "ÇÖZÜLDÜ" },
  "todo.noTasks": { en: "No active objectives. Enjoy the peace. 🧘‍♂️", tr: "Aktif hedef yok. Huzurun tadını çıkarın. 🧘‍♂️" },
  "todo.done": { en: "DONE", tr: "TAMAM" },
  "todo.enrolled": { en: "ENROLLED", tr: "KAYITLI" },
  "todo.stayFocused": { en: "STAY FOCUSED • ACTIVE STATUS", tr: "ODAKLANIN • AKTİF DURUM" },
  "todo.successToast": { en: "Mission added to log! 🚀", tr: "Görev günlüğe eklendi! 🚀" },
  "todo.deleteToast": { en: "Objective deleted. 🗑️", tr: "Hedef silindi. 🗑️" },
  "planner.title": { en: "AI Career Architect", tr: "AI Kariyer Mimarı" },
  "planner.desc": { en: "Based on your profile, I can build a step-by-step masterplan for your success. Want to focus on something specific?", tr: "Profilinize dayanarak, başarınız için adım adım bir ana plan oluşturabilirim. Özel bir şeye odaklanmak ister misiniz?" },
  "planner.placeholder": { en: "e.g., I want to focus on React and AI integration...", tr: "ör. React ve AI entegrasyonuna odaklanmak istiyorum..." },
  "planner.generateBtn": { en: "Generate My Flowchart", tr: "Yol Haritamı Oluştur" },
  "planner.thinking": { en: "Thinking deeply...", tr: "Derinlemesine düşünülüyor..." },
  "jobBoard.title": { en: "OPPORTUNITY RADAR", tr: "FIRSAT RADARI" },
  "jobBoard.refresh": { en: "REFRESH", tr: "YENİLE" },
  "jobBoard.viewMission": { en: "VIEW MISSION", tr: "GÖREVİ GÖR" },
  "jobBoard.empty": { en: "No active signals found for your expertise. Try adding more skills to your profile! 📡", tr: "Uzmanlığınız için aktif sinyal bulunamadı. Profilinize yeni beceriler eklemeyi deneyin! 📡" },
  "jobBoard.successToast": { en: "Job board synchronized! 📡", tr: "İş panosu senkronize edildi! 📡" },
  "jobBoard.failToast": { en: "Failed to fetch job opportunities.", tr: "İş fırsatları alınamadı." },

  // ==========================================
  // REGISTER PAGE
  // ==========================================
  "register.joinThe": { en: "Join the", tr: "Geleceğe" },
  "register.future": { en: "Future", tr: "Katıl" },
  "register.subtitle": { en: "Create your account to unlock full potential.", tr: "Tam potansiyelinizi açmak için hesabınızı oluşturun." },
  "register.fullName": { en: "Full Name", tr: "Ad Soyad" },
  "register.emailLabel": { en: "Email Address", tr: "E-posta Adresi" },
  "register.passwordLabel": { en: "Secure Password", tr: "Güvenli Şifre" },
  "register.startFree": { en: "Start for Free", tr: "Ücretsiz Başla" },
  "register.alreadyMember": { en: "Already part of the ecosystem?", tr: "Zaten üye misiniz?" },
  "register.signIn": { en: "Sign In Securely", tr: "Güvenli Giriş Yap" },
  "register.success": { en: "Account created! Check your email, love! 📧", tr: "Hesap oluşturuldu! E-postanızı kontrol edin! 📧" },
  "register.fail": { en: "Registration failed. Email might be taken.", tr: "Kayıt başarısız. E-posta kullanılıyor olabilir." },
  "register.heroBadge": { en: "Fast setup", tr: "Hizli kurulum" },
  "register.heroPointOne": { en: "Create your account and move straight into profile onboarding.", tr: "Hesabinizi olusturun ve dogrudan profil kurulumuna gecin." },
  "register.heroPointTwo": { en: "Get personalized internships, jobs, and local recommendations.", tr: "Size ozel staj, is ve yerel oneriler alin." },
  "register.heroPointThree": { en: "Keep your profile ready for the web experience without touching mobile yet.", tr: "Mobil uygulamaya dokunmadan web deneyimi icin profilinizi hazir tutun." },
  "register.metricOne": { en: "steps to launch", tr: "adimda baslangic" },
  "register.metricTwo": { en: "profile path", tr: "profil akisi" },
  "register.panelTitle": { en: "Create your account", tr: "Hesabinizi olusturun" },
  "register.panelSubtitle": { en: "Start with the essentials now. We will shape the rest in onboarding.", tr: "Simdilik temel bilgileri girin. Kalanini onboarding icinde sekillendirecegiz." },
  "register.passwordPlaceholder": { en: "Choose something strong", tr: "Guclu bir sifre secin" },
  "register.termsHint": { en: "By continuing, you are setting up your EverydayLife workspace and profile flow.", tr: "Devam ederek EverydayLife calisma alaninizi ve profil akisinizi kuruyorsunuz." },

  // ==========================================
  // BOARDING PAGE
  // ==========================================
  "boarding.title": { en: "Welcome Aboard!", tr: "Hoş Geldiniz!" },
  "boarding.subtitle": { en: "Let's personalize your EverydayLife experience.", tr: "EverydayLife deneyiminizi kişiselleştirelim." },
  "boarding.uploadPhoto": { en: "Upload Photo 📸", tr: "Fotoğraf Yükle 📸" },
  "boarding.location": { en: "Location", tr: "Konum" },
  "boarding.country": { en: "Country", tr: "Ülke" },
  "boarding.city": { en: "City", tr: "Şehir" },
  "boarding.careerSkills": { en: "Career & Skills", tr: "Kariyer & Beceriler" },
  "boarding.occupation": { en: "Field of Interest / Occupation", tr: "İlgi Alanı / Meslek" },
  "boarding.phone": { en: "Phone Number 📞", tr: "Telefon Numarası 📞" },
  "boarding.isStudent": { en: "Are you currently a Student? 🎓", tr: "Şu an öğrenci misiniz? 🎓" },
  "boarding.major": { en: "What is your Major?", tr: "Bölümünüz nedir?" },
  "boarding.university": { en: "University Name", tr: "Üniversite Adı" },
  "boarding.experience": { en: "Experience Level", tr: "Deneyim Seviyesi" },
  "boarding.stars": { en: "Stars", tr: "Yıldız" },
  "boarding.beginner": { en: "Beginner", tr: "Başlangıç" },
  "boarding.expert": { en: "Expert", tr: "Uzman" },
  "boarding.hobbies": { en: "Hobbies & Passion 🎨 (Comma separated)", tr: "Hobiler & Tutkular 🎨 (Virgülle ayırın)" },
  "boarding.skills": { en: "Expertise & Skills 🛠️ (Search & Pick)", tr: "Uzmanlık & Beceriler 🛠️ (Ara & Seç)" },
  "boarding.searchSkills": { en: "Search skills (e.g. Python, DevOps...)", tr: "Beceri ara (ör. Python, DevOps...)" },
  "boarding.selected": { en: "Selected", tr: "Seçilen" },
  "boarding.save": { en: "Save & Continue 🚀", tr: "Kaydet & Devam Et 🚀" },
  "boarding.success": { en: "Profile Setup Complete! You look great! 🚀", tr: "Profil Kurulumu Tamamlandı! Harika görünüyorsunuz! 🚀" },
  "boarding.fail": { en: "Could not save profile. Please try again.", tr: "Profil kaydedilemedi. Lütfen tekrar deneyin." },
  "boarding.stepIdentity": { en: "Identity", tr: "Kimlik" },
  "boarding.stepJourney": { en: "Journey", tr: "Yolculuk" },
  "boarding.stepFinish": { en: "Finish", tr: "Bitir" },
  "boarding.prefill": { en: "We pulled in your Google profile so you can move faster.", tr: "Daha hızlı ilerlemeniz için Google profilinizi içeri aldık." },
  "boarding.next": { en: "Next Step", tr: "Sonraki Adım" },
  "boarding.back": { en: "Back", tr: "Geri" },
  "boarding.letsStart": { en: "Let's Start", tr: "Başlayalım" },
  "boarding.name": { en: "Full Name", tr: "Ad Soyad" },
  "boarding.email": { en: "Email", tr: "E-posta" },
  "boarding.photoHint": { en: "You can keep your Google photo or upload a new one.", tr: "Google fotoğrafınızı kullanabilir veya yenisini yükleyebilirsiniz." },
  "boarding.aboutYou": { en: "Tell us about your direction and what you want to build.", tr: "Bize yönünüzü ve ne inşa etmek istediğinizi anlatın." },
  "boarding.studentOn": { en: "Student mode on", tr: "Ogrenci modu acik" },
  "boarding.studentOff": { en: "Student mode off", tr: "Ogrenci modu kapali" },
  "boarding.studentHintOn": { en: "We'll include your academic profile in the setup.", tr: "Kurulumda akademik profilinizi de kullanacagiz." },
  "boarding.studentHintOff": { en: "Skip this if you're not studying right now.", tr: "Su anda ogrenci degilseniz bu bolumu atlayabilirsiniz." },
  "boarding.fullNamePlaceholder": { en: "Your full name", tr: "Adiniz ve soyadiniz" },
  "boarding.countryPlaceholder": { en: "e.g. Turkey", tr: "orn. Turkiye" },
  "boarding.cityPlaceholder": { en: "e.g. Istanbul", tr: "orn. Istanbul" },
  "boarding.phonePlaceholder": { en: "e.g. +90 5XX XXX XX XX", tr: "orn. +90 5XX XXX XX XX" },
  "boarding.majorPlaceholder": { en: "e.g. Computer Science", tr: "orn. Bilgisayar Muhendisligi" },
  "boarding.universityPlaceholder": { en: "e.g. Istanbul Technical University", tr: "orn. Istanbul Teknik Universitesi" },
  "boarding.interestsPlaceholder": { en: "e.g. Coding, Gaming, Travel", tr: "orn. Kodlama, Oyun, Seyahat" },
  "navigation.inbox": { en: "Inbox", tr: "Gelen Kutusu" },
  "inbox.title": { en: "My Inbox", tr: "Mesajlarım" },
  "inbox.empty": { en: "No messages yet.", tr: "Henüz mesaj yok." },
  "inbox.regarding": { en: "Re:", tr: "Hakkında:" },
  "notif.title": { en: "Notifications", tr: "Bildirimler" },
  "notif.refresh": { en: "Refresh", tr: "Yenile" },
  "notif.caughtUp": { en: "All caught up!", tr: "Her şey tamam!" },
  "notif.cvReady": { en: "Your CV is ready to view!", tr: "CV'niz görüntülenmeye hazır!" },
  "notif.cvBody": { en: "Update your Personal Summary to boost your score.", tr: "Puanınızı artırmak için Kişisel Özetinizi güncelleyin." },
  "notif.internReady": { en: "New internships available 🎓", tr: "Yeni stajlar mevcut 🎓" },
  "notif.internBody": { en: "Fresh AI-generated missions are now open. Enroll before spots fill!", tr: "AI tarafından oluşturulan yeni görevler açık. Kontenjan dolmadan kaydolun!" },
  "notif.vibeReady": { en: "Local Vibes refreshed ✨", tr: "Yerel Havalar yenilendi ✨" },
  "notif.vibeBody": { en: "New events and deals in your city are available.", tr: "Şehrinizdeki yeni etkinlikler ve fırsatlar sizi bekliyor." },
  "notif.roadmapReady": { en: "Career Blueprint unlocked 🗺️", tr: "Kariyer Yol Haritası açıldı 🗺️" },
  "notif.roadmapBody": { en: "Generate your roadmap for this week to stay on track.", tr: "Yolunda kalmak için bu haftaki yol haritanızı oluşturun." },
  "notif.marketReady": { en: "Marketplace has new items 🛒", tr: "Marketplace'te yeni ürünler var 🛒" },
  "notif.marketBody": { en: "Someone just listed a new product. Check the marketplace!", tr: "Birisi yeni bir ürün listeledi. Marketplace'i kontrol edin!" },
  "notif.deadlineTitle": { en: "Internship Deadline Approaching ⏳", tr: "Staj Teslim Tarihi Yaklaşıyor ⏳" },
  "notif.deadlineBody": { en: "\"{title}\" is still active. Don't forget to submit!", tr: "\"{title}\" hala aktif. Teslim etmeyi unutmayın!" },
  "notif.cvScoreTitle": { en: "Your CV Score is {score}/100 📝", tr: "CV Puanınız {score}/100 📝" },
  "notif.cvScoreBody": { en: "Complete missing sections to boost your profile strength!", tr: "Profil gücünüzü artırmak için eksik bölümleri tamamlayın!" },

  // ==========================================
  // DASHBOARD
  // ==========================================
  "dashboard.systemActive": { en: "System", tr: "Sistem" },
  "dashboard.active": { en: "Active", tr: "Aktif" },
  "dashboard.subtitle": { en: "Your intelligent orchestration layer for career and lifestyle.", tr: "Kariyer ve yaşam tarzınız için akıllı orkestrasyon katmanı." },
  "dashboard.aiSync": { en: "AI SYNC: OPTIMAL", tr: "AI SENK: OPTİMAL" },
  "dashboard.careerProgress": { en: "Career Progress", tr: "Kariyer İlerlemesi" },
  "dashboard.stats": { en: "Stats", tr: "İstatistikler" },
  "dashboard.missions": { en: "Missions", tr: "Görevler" },
  "dashboard.tasks": { en: "Tasks", tr: "Görevler" },
  "dashboard.avgScore": { en: "Avg Score", tr: "Ort. Puan" },
  "dashboard.jobs": { en: "Jobs", tr: "İşler" },
  "dashboard.jobsSub": { en: "Live Openings", tr: "Açık Pozisyonlar" },
  "dashboard.internships": { en: "Internships", tr: "Stajlar" },
  "dashboard.internshipsSub": { en: "AI Missions", tr: "AI Görevleri" },
  "dashboard.marketplace": { en: "Marketplace", tr: "Pazar Yeri" },
  "dashboard.marketplaceSub": { en: "Trade Gear", tr: "Alım Satım" },
  "dashboard.localInsights": { en: "Local Insights", tr: "Yerel Bilgiler" },
  "dashboard.localInsightsSub": { en: "City Vibes & Deals", tr: "Şehir Fırsatları" },
  "dashboard.growthSystems": { en: "Growth Systems", tr: "Gelişim Sistemleri" },
  "dashboard.autoSync": { en: "Auto-Sync", tr: "Oto-Senk" },
  "dashboard.liveCv": { en: "Live", tr: "Canlı" },
  "dashboard.cvBuilder": { en: "CV Builder", tr: "CV Oluşturucu" },
  "dashboard.cvSubtitle": { en: "Generate, style, and track your master resume. Click to edit.", tr: "Özgeçmişinizi oluşturun, şekillendirin ve takip edin." },
  "dashboard.profileStrength": { en: "Profile Strength", tr: "Profil Gücü" },
  "dashboard.localVibes": { en: "Local Vibes", tr: "Yerel Keşifler" },
  "dashboard.viewAll": { en: "View All", tr: "Tümünü Gör" },
  "dashboard.missionLog": { en: "Mission Log", tr: "Görev Kaydı" },

  // ==========================================
  // INTERNSHIPS
  // ==========================================
  "internships.title": { en: "Internship", tr: "Staj" },
  "internships.hub": { en: "Hub", tr: "Merkezi" },
  "internships.subtitle": { en: "AI-generated missions. Enroll, learn, get certified.", tr: "AI tarafından oluşturulan görevler. Kayıt olun, öğrenin, sertifika alın." },
  "internships.generate": { en: "Generate New Missions", tr: "Yeni Görevler Oluştur" },
  "internships.loadSavedBtn": { en: "Load Saved", tr: "Kayitli Yukle" },
  "internships.refreshBtn": { en: "Refresh Internships", tr: "Stajlari Yenile" },
  "internships.generating": { en: "Generating...", tr: "Oluşturuluyor..." },
  "internships.enrolled": { en: "Enrolled", tr: "Kayıtlı" },
  "internships.graded": { en: "Graded", tr: "Notlandı" },
  "internships.new": { en: "New", tr: "Yeni" },
  "internships.explore": { en: "Explore", tr: "Keşfet" },
  "internships.score": { en: "Score", tr: "Puan" },
  "internships.days": { en: "days", tr: "gün" },
  "internships.generateSuccess": { en: "Opportunities Generated! 🚀", tr: "Fırsatlar Oluşturuldu! 🚀" },
  "internships.generatingToast": { en: "AI is crafting your career path... 🤖", tr: "AI kariyer yolunuzu şekillendiriyor... 🤖" },
  "internships.generateFail": { en: "Generation failed. Check API keys.", tr: "Oluşturma başarısız. API anahtarlarını kontrol edin." },
  "internships.statusCompleted": { en: "COMPLETED", tr: "TAMAMLANDI" },
  "internships.statusActive": { en: "ACTIVE", tr: "AKTİF" },
  "internships.statusNew": { en: "NEW", tr: "YENİ" },
  "internships.loading": { en: "Loading your career path...", tr: "Kariyer yolunuz yükleniyor..." },
  "internships.emptyTitle": { en: "Your portfolio is empty! 📄", tr: "Portföyünüz boş! 📄" },
  "internships.emptySubtitle": { en: "Generate your first set of internships to get started.", tr: "Başlamak için ilk staj setinizi oluşturun." },
  "internships.launchAI": { en: "Launch AI Generation", tr: "AI Oluşturmayı Başlat" },
  "internships.projectBased": { en: "Project Based", tr: "Proje Tabanlı" },
  "internships.passed": { en: "PASSED", tr: "GEÇTİ" },
  "internships.inProgress": { en: "IN PROGRESS", tr: "DEVAM EDİYOR" },
  "internships.active": { en: "ACTIVE", tr: "AKTİF" },
  "internships.viewMission": { en: "VIEW MISSION", tr: "GÖREVİ GÖR" },

  // ==========================================
  // INTERNSHIP DETAIL
  // ==========================================
  "internDetail.loading": { en: "Loading mission data...", tr: "Görev verileri yükleniyor..." },
  "internDetail.enrolledToast": { en: "Enrolled! ⏱️", tr: "Kayıt Olundu! ⏱️" },
  "internDetail.enrollFail": { en: "Could not enroll.", tr: "Kayıt olunamadı." },
  "internDetail.syncSuccess": { en: "Tutorials synced! 📺", tr: "Eğitimler senkronize edildi! 📺" },
  "internDetail.syncFail": { en: "Sync failed.", tr: "Senkronizasyon başarısız." },
  "internDetail.gradingToast": { en: "AI is analyzing your code... 🧠", tr: "AI kodunuzu analiz ediyor... 🧠" },
  "internDetail.projectAccepted": { en: "Project Accepted! 🎉", tr: "Proje Kabul Edildi! 🎉" },
  "internDetail.needsRevision": { en: "Needs revision.", tr: "Revizyon gerekiyor." },
  "internDetail.submitFail": { en: "Submission failed.", tr: "Gönderim başarısız." },
  "internDetail.quizGenerating": { en: "AI is generating your exam... 📝", tr: "AI sınavınızı oluşturuyor... 📝" },
  "internDetail.quizFail": { en: "Quiz generation failed.", tr: "Sınav oluşturma başarısız." },
  "internDetail.quizPassed": { en: "🎉 You PASSED! Certificate unlocked!", tr: "🎉 GEÇTİNİZ! Sertifika açıldı!" },
  "internDetail.quizFailedScore": { en: "Score: {score}%. Need 60% to pass.", tr: "Puan: %{score}. Geçmek için %60 gerekiyor." },
  "internDetail.back": { en: "Back to Internships", tr: "Stajlara Geri Dön" },
  "internDetail.difficulty": { en: "Difficulty", tr: "Zorluk" },
  "internDetail.intermediate": { en: "Intermediate", tr: "Orta" },
  "internDetail.aiBriefing": { en: "AI Briefing", tr: "AI Bilgilendirmesi" },
  "internDetail.skillsTitle": { en: "Skills You Will Master", tr: "Ustalaşacağınız Beceriler" },
  "internDetail.playlistTitle": { en: "Learning Playlist", tr: "Öğrenme Listesi" },
  "internDetail.sync": { en: "SYNC", tr: "SENKRO" },
  "internDetail.watch": { en: "Watch", tr: "İzle" },
  "internDetail.findingTutorials": { en: "AI is finding tutorials...", tr: "AI eğitim videoları buluyor..." },
  "internDetail.forceSync": { en: "FORCE SYNC", tr: "ZORLA SENKRO" },
  "internDetail.consoleTitle": { en: "Project Console", tr: "Proje Konsolu" },
  "internDetail.readyTitle": { en: "Ready to Launch?", tr: "Başlamaya Hazır mısın?" },
  "internDetail.readySubtitle": { en: "Start the timer and begin.", tr: "Zamanlayıcıyı başlat ve başla." },
  "internDetail.starting": { en: "Starting...", tr: "Başlatılıyor..." },
  "internDetail.startBtn": { en: "START INTERNSHIP 🚀", tr: "STAJA BAŞLA 🚀" },
  "internDetail.missionActiveBadge": { en: "MISSION ACTIVE", tr: "GÖREV AKTİF" },
  "internDetail.takeExamBtn": { en: "TAKE CERTIFICATION EXAM", tr: "SERTİFİKA SINAVINA GİR" },
  "internDetail.orSubmit": { en: "OR SUBMIT PROJECT", tr: "VEYA PROJE GÖNDER" },
  "internDetail.githubLabel": { en: "GitHub Repo", tr: "GitHub Deposu" },
  "internDetail.daysLabel": { en: "Days", tr: "Gün" },
  "internDetail.complexityLabel": { en: "Complexity", tr: "Karmaşıklık" },
  "internDetail.grading": { en: "GRADING...", tr: "NOTLANDIRILIYOR..." },
  "internDetail.submitBtn": { en: "SUBMIT PROJECT 📤", tr: "PROJEYİ GÖNDER 📤" },
  "internDetail.certified": { en: "Certified! 🏆", tr: "Sertifikalı! 🏆" },
  "internDetail.needsImprovement": { en: "Needs Improvement", tr: "Geliştirilmeli" },
  "internDetail.feedbackLabel": { en: "Feedback", tr: "Geri Bildirim" },
  "internDetail.viewCertBtn": { en: "VIEW CERTIFICATE", tr: "SERTİFİKAYI GÖR" },
  "internDetail.retryBtn": { en: "RETRY", tr: "TEKRAR DENE" },
  "internDetail.examModalTitle": { en: "Certification Exam", tr: "Sertifika Sınavı" },
  "internDetail.quizPassedTitle": { en: "🎉 PASSED!", tr: "🎉 GEÇTİNİZ!" },
  "internDetail.quizFailedTitle": { en: "❌ FAILED", tr: "❌ KALDINIZ" },
  "internDetail.correctLabel": { en: "correct", tr: "doğru" },
  "internDetail.certUnlocked": { en: "Certificate unlocked!", tr: "Sertifika açıldı!" },
  "internDetail.needPass": { en: "Need 60% to pass.", tr: "Geçmek için %60 gerekiyor." },
  "internDetail.questionPrefix": { en: "Q", tr: "S" },
  "internDetail.answeredLabel": { en: "answered", tr: "cevaplandı" },
  "internDetail.submitExamBtnFinal": { en: "SUBMIT EXAM ✓", tr: "SINAVI GÖNDER ✓" },
  "internDetail.certTitle": { en: "CERTIFICATE OF COMPLETION", tr: "BAŞARI SERTİFİKASI" },
  "internDetail.certCertifies": { en: "This certifies that", tr: "Bu belge," },
  "internDetail.certBody": { en: "has successfully completed the internship", tr: "stajını başarıyla tamamladığını onaylar" },
  "internDetail.certFooter": { en: "EverydayLife AI Career Accelerator", tr: "EverydayLife AI Kariyer Hızlandırıcı" },
  "internDetail.downloadCertBtn": { en: "Download Certificate", tr: "Sertifikayı İndir" },

  // ==========================================
  // JOBS / FIND JOBS
  // ==========================================
  "jobs.title": { en: "Job", tr: "İş" },
  "jobs.radar": { en: "Radar", tr: "Radarı" },
  "common.student": { en: "Student", tr: "Öğrenci" },
  "common.notFound": { en: "Not found.", tr: "Bulunamadı." },
  "common.failed": { en: "Failed.", tr: "Başarısız." },
  "common.close": { en: "CLOSE", tr: "KAPAT" },
  "common.prev": { en: "PREV", tr: "GERİ" },
  "common.next": { en: "NEXT", tr: "İLERİ" },
  "jobs.subtitle": { en: "AI-powered job discovery tailored to your profile.", tr: "Profilinize özel AI destekli iş keşfi." },
  "jobs.search": { en: "Search jobs...", tr: "İş ara..." },
  "jobs.location": { en: "Location...", tr: "Konum..." },
  "jobs.searchBtn": { en: "Search", tr: "Ara" },
  "jobs.apply": { en: "Apply", tr: "Başvur" },
  "jobs.noJobs": { en: "No jobs found. Try searching!", tr: "İş bulunamadı. Arama yapmayı deneyin!" },
  "jobs.scanningToast": { en: "Scanning for \"{query}\" jobs... 🕵️", tr: "\"{query}\" işleri aranıyor... 🕵️" },
  "jobs.foundToast": { en: "Found {count} jobs! 💼", tr: "{count} iş bulundu! 💼" },
  "jobs.noJobsFoundToast": { en: "No jobs found. Try different keywords.", tr: "İş bulunamadı. Farklı kelimeler deneyin." },
  "jobs.scrapeFailToast": { en: "Scraping failed. Please try again.", tr: "Arama başarısız. Lütfen tekrar deneyin." },
  "jobs.headerTitlePrefix": { en: "Find Your", tr: "Hayalindeki" },
  "jobs.headerTitleSuffix": { en: "Dream Job", tr: "İşi Bul" },
  "jobs.headerSubtitle": { en: "We scrape the web, so you can focus on building the future.", tr: "Geleceği inşa etmeye odaklanabilmeniz için web'i tarıyoruz." },
  "jobs.myProfileBtn": { en: "MY PROFILE", tr: "PROFİLİM" },
  "jobs.customSearchBtn": { en: "CUSTOM SEARCH", tr: "ÖZEL ARAMA" },
  "jobs.titleLabel": { en: "Job Title / Skill", tr: "İş Başlığı / Beceri" },
  "jobs.titlePlaceholder": { en: "e.g. Python Developer", tr: "ör. Python Geliştirici" },
  "jobs.locationLabel": { en: "Location", tr: "Konum" },
  "jobs.locationPlaceholder": { en: "e.g. Remote / New York", tr: "ör. Uzaktan / İstanbul" },
  "jobs.searchBtn": { en: "SEARCH", tr: "ARA" },
  "jobs.loadSavedBtn": { en: "Load Saved", tr: "Kayitli Yukle" },
  "jobs.refreshBtn": { en: "Refresh Jobs", tr: "Isleri Yenile" },
  "jobs.refreshingToast": { en: "Refreshing \"{query}\" jobs... 🔄", tr: "\"{query}\" isleri yenileniyor... 🔄" },
  "jobs.savedSnapshot": { en: "Showing saved jobs for {query} in {location}", tr: "{location} konumunda {query} icin kayitli isler gosteriliyor" },
  "jobs.loadingResults": { en: "Scanning Planet Earth for Roles...", tr: "Dünya çapında işler taranıyor..." },
  "jobs.newBadge": { en: "New", tr: "Yeni" },
  "jobs.remote": { en: "Remote", tr: "Uzaktan" },
  "jobs.fullTime": { en: "Full-Time", tr: "Tam Zamanlı" },
  "jobs.applyOnSource": { en: "Apply on {source}", tr: "{source} üzerinden başvur" },
  "jobs.zeroSignalsTitle": { en: "Zero Signals", tr: "Sinyal Yok" },
  "jobs.zeroSignalsSubtitle": { en: "Hit Search to scan for opportunities matching your profile.", tr: "Profilinize uygun fırsatları aramak için Ara'ya basın." },

  // ==========================================
  // MARKETPLACE
  // ==========================================
  "market.title": { en: "Student", tr: "Öğrenci" },
  "market.marketplace": { en: "Marketplace", tr: "Pazar Yeri" },
  "market.subtitle": { en: "Buy, sell, and trade with fellow students.", tr: "Öğrenci arkadaşlarınızla alışveriş yapın." },
  "market.sell": { en: "Sell Something", tr: "Ürün Sat" },
  "market.inbox": { en: "Inbox", tr: "Gelen Kutusu" },
  "market.noProducts": { en: "No products yet.", tr: "Henüz ürün yok." },
  "market.contact": { en: "Contact Seller", tr: "Satıcıya Ulaş" },
  "market.price": { en: "Price", tr: "Fiyat" },
  "market.headerTitlePrefix": { en: "Everyday", tr: "HerGün" },
  "market.headerTitleSuffix": { en: "Market", tr: "Pazar" },
  "market.headerSubtitle": { en: "Exclusive gear for your career and life journey.", tr: "Kariyer ve yaşam yolculuğunuz için özel ekipmanlar." },
  "market.searchPlaceholder": { en: "Search items, sellers...", tr: "Ürün, satıcı ara..." },
  "market.resultsFor": { en: "{count} results for \"{query}\"", tr: "\"{query}\" için {count} sonuç" },
  "market.resultFor": { en: "1 result for \"{query}\"", tr: "\"{query}\" için 1 sonuç" },
  "market.sellBtn": { en: "Sell an Item", tr: "Ürün Sat" },
  "market.loading": { en: "Loading the market...", tr: "Pazar yükleniyor..." },
  "market.viewDetails": { en: "View Details →", tr: "Detayları Gör →" },
  "market.noResults": { en: "No results for \"{query}\"", tr: "\"{query}\" için sonuç yok" },
  "market.noItems": { en: "No items yet!", tr: "Henüz ürün yok!" },
  "market.tryDifferent": { en: "Try a different keyword.", tr: "Farklı bir kelime deneyin." },
  "market.firstToList": { en: "Be the first to list something!", tr: "İlk ürünü siz ekleyin!" },
  "market.startSelling": { en: "Start Selling", tr: "Satışa Başla" },
  "market.startSelling": { en: "Start Selling", tr: "Satışa Başla" },

  // ==========================================
  // PRODUCT DETAIL
  // ==========================================
  "product.back": { en: "Back to Marketplace", tr: "Pazara Geri Dön" },
  "product.sellerLabel": { en: "Seller", tr: "Satıcı" },
  "product.verifiedLabel": { en: "Verified User", tr: "Doğrulanmış Kullanıcı" },
  "product.chatTitle": { en: "Negotiation Chat", tr: "Pazarlık Sohbeti" },
  "product.messagePlaceholder": { en: "Message...", tr: "Mesaj..." },
  "product.offerPlaceholder": { en: "Offer Price", tr: "Teklif Fiyatı" },
  "product.offerBtn": { en: "Offer", tr: "Teklif Ver" },
  "product.offerSentToast": { en: "Offer Sent!", tr: "Teklif Gönderildi!" },
  "profile.memberSince": { en: "Member Since", tr: "Üyelik Tarihi" },
  "profile.verified": { en: "Verified Profile", tr: "Doğrulanmış Profil" },
  "profile.editIdentity": { en: "Edit Identity", tr: "Kimliği Düzenle" },
  "profile.cancelEdit": { en: "Cancel Edit", tr: "Düzenlemeyi İptal Et" },
  "profile.professional": { en: "Professional", tr: "Profesyonel" },
  "profile.location": { en: "Location", tr: "Konum" },
  "profile.rating": { en: "Rating", tr: "Derecelendirme" },
  "profile.stars": { en: "{count} Experience Stars", tr: "{count} Deneyim Yıldızı" },
  "profile.studentProfile": { en: "Student Profile", tr: "Öğrenci Profili" },
  "profile.currentlyAt": { en: "Currently at {uni} pursuing a major in {major}", tr: "Şu anda {uni} bünyesinde {major} ana dalında eğitim görüyor" },
  "profile.expertise": { en: "EXPERTISE & SKILLS", tr: "UZMANLIK VE BECERİLER" },
  "profile.noSkills": { en: "No skills listed. Launch your profile settings to add some! 🚀", tr: "Beceri listelenmemiş. Eklemek için profil ayarlarınızı açın! 🚀" },
  "profile.myCertificates": { en: "MY CERTIFICATES", tr: "SERTİFİKALARIM" },
  "profile.certified": { en: "CERTIFIED", tr: "SERTİFİKALI" },
  "profile.viewCert": { en: "View Certificate", tr: "Sertifikayı Görüntüle" },
  "profile.fullName": { en: "Full Name", tr: "Ad Soyad" },
  "profile.namePlaceholder": { en: "Enter your name", tr: "Adınızı girin" },
  "profile.occupation": { en: "Occupation", tr: "Meslek" },
  "profile.university": { en: "University", tr: "Üniversite" },
  "profile.major": { en: "Major", tr: "Bölüm" },
  "profile.phone": { en: "Phone Number", tr: "Telefon Numarası" },
  "profile.country": { en: "Country", tr: "Ülke" },
  "profile.city": { en: "City", tr: "Şehir" },
  "profile.skillSearch": { en: "Expertise & Skills 🛠️ (Search & Pick)", tr: "Uzmanlık ve Beceriler 🛠️ (Ara ve Seç)" },
  "profile.skillPlaceholder": { en: "Find skills (e.g. React, Docker...)", tr: "Beceri bul (ör. React, Docker...)" },
  "profile.skillHint": { en: "Pick the technologies and skills you own.", tr: "Sahip olduğunuz teknolojileri ve becerileri seçin." },
  "profile.updateSuccess": { en: "Profile Updated! ✨", tr: "Profil Güncellendi! ✨" },
  "profile.accountActions": { en: "ACCOUNT ACTIONS", tr: "HESAP ISLEMLERI" },
  "profile.logoutCta": { en: "Log Out", tr: "Cikis Yap" },
  "profile.deleteCta": { en: "Delete Account", tr: "Hesabi Sil" },
  "profile.logoutHint": { en: "Sign out on this device and keep your account safe.", tr: "Bu cihazdaki oturumu kapatin ve hesabinizi koruyun." },
  "profile.deleteHint": { en: "Permanently remove your profile, progress, and marketplace activity.", tr: "Profilinizi, ilerlemenizi ve pazar hareketlerinizi kalici olarak silin." },
  "profile.deleteConfirm": { en: "Delete your account permanently? This cannot be undone.", tr: "Hesabinizi kalici olarak silmek istiyor musunuz? Bu geri alinamaz." },
  "profile.deleteSuccess": { en: "Account deleted.", tr: "Hesap silindi." },
  "roadmap.headerTitle": { en: "Architectural", tr: "Kariyer" },
  "roadmap.headerSubtitle": { en: "Blueprint", tr: "Yol Haritası" },
  "roadmap.headerDesc": { en: "Your personalized step-by-step master plan for success.", tr: "Başarı için kişiselleştirilmiş adım adım ana planınız." },
  "roadmap.stepLabel": { en: "Step", tr: "Adım" },
  "roadmap.goalReached": { en: "Goal Reached!", tr: "Hedefe Ulaşıldı!" },
  "roadmap.noStrategy": { en: "No Strategy Found", tr: "Strateji Bulunamadı" },
  "roadmap.backToDashboard": { en: "Back to Dashboard", tr: "Panele Geri Dön" },
  "product.offerSentToast": { en: "Offer Sent!", tr: "Teklif Gönderildi!" },

  // ==========================================
  // CREATE PRODUCT
  // ==========================================
  "marketCreate.title": { en: "Sell an Item", tr: "Ürün Sat" },
  "marketCreate.itemTitle": { en: "Title", tr: "Başlık" },
  "marketCreate.itemTitlePlaceholder": { en: "What are you selling?", tr: "Ne satıyorsunuz?" },
  "marketCreate.price": { en: "Price ($)", tr: "Fiyat ($)" },
  "marketCreate.condition": { en: "Condition", tr: "Durum" },
  "marketCreate.new": { en: "New", tr: "Yeni" },
  "marketCreate.used": { en: "Used / Old", tr: "Kullanılmış / Eski" },
  "marketCreate.description": { en: "Description", tr: "Açıklama" },
  "marketCreate.photos": { en: "Photos (Max 3)", tr: "Fotoğraflar (En fazla 3)" },
  "marketCreate.listBtn": { en: "List Item Now 🚀", tr: "Ürünü Hemen Listele 🚀" },
  "marketCreate.successToast": { en: "Item Listed Successfully! 💰", tr: "Ürün Başarıyla Listelendi! 💰" },
  "marketCreate.failToast": { en: "Failed to list item.", tr: "Ürün listelenemedi." },

  // ==========================================
  // DISCOUNTS / LOCAL
  // ==========================================
  "discounts.title": { en: "Local", tr: "Yerel" },
  "discounts.vibes": { en: "Vibes", tr: "Keşifler" },
  "discounts.subtitle": { en: "Deals, events, food & career vibes in your city.", tr: "Şehrinizdeki fırsatlar, etkinlikler, yemek ve kariyer." },
  "discounts.refresh": { en: "Refresh", tr: "Yenile" },
  "discounts.deal": { en: "Deal", tr: "Fırsat" },
  "discounts.event": { en: "Event", tr: "Etkinlik" },
  "discounts.food": { en: "Food", tr: "Yemek" },
  "discounts.career": { en: "Career", tr: "Kariyer" },

  // ==========================================
  // TRAVEL PLANNER
  // ==========================================
  "travel.title": { en: "Travel", tr: "Seyahat" },
  "travel.planner": { en: "Planner", tr: "Planı" },
  "travel.from": { en: "From", tr: "Nereden" },
  "travel.to": { en: "To", tr: "Nereye" },
  "travel.date": { en: "Date", tr: "Tarih" },
  "travel.plan": { en: "Plan Trip", tr: "Seyahat Planla" },
  "travel.flights": { en: "Search Flights", tr: "Uçuş Ara" },

  // ==========================================
  // CV BUILDER
  // ==========================================
  "cv.title": { en: "CV", tr: "CV" },
  "cv.builder": { en: "Builder", tr: "Oluşturucu" },
  "cv.subtitle": { en: "Build your professional resume.", tr: "Profesyonel özgeçmişinizi oluşturun." },
  "cv.save": { en: "Save CV", tr: "CV Kaydet" },
  "cv.download": { en: "Download PDF", tr: "PDF İndir" },
  "cv.summary": { en: "Summary", tr: "Özet" },
  "cv.skills": { en: "Skills", tr: "Beceriler" },
  "cv.workExperience": { en: "Work Experience", tr: "İş Deneyimi" },
  "cv.education": { en: "Education", tr: "Eğitim" },

  // ==========================================
  // PROFILE
  // ==========================================
  "profile.title": { en: "Profile", tr: "Profil" },
  "profile.settings": { en: "Settings", tr: "Ayarlar" },
  "profile.editProfile": { en: "Edit Profile", tr: "Profili Düzenle" },
  "profile.save": { en: "Save Changes", tr: "Değişiklikleri Kaydet" },
  "profile.memberSince": { en: "Member Since", tr: "Üyelik Tarihi" },
  "discounts.headerTitlePrefix": { en: "Local", tr: "Yerel" },
  "discounts.headerTitleSuffix": { en: "Vibes", tr: "Hava" },
  "discounts.headerSubtitle": { en: "Curated experiences in {location}", tr: "{location} konumundaki özel deneyimler" },
  "discounts.yourCity": { en: "your city", tr: "şehriniz" },
  "discounts.lastUpdated": { en: "Last updated {time}", tr: "Son guncelleme {time}" },
  "discounts.liveBadge": { en: "live from Gemini", tr: "Gemini ile yenilendi" },
  "discounts.loadSavedBtn": { en: "Load Saved", tr: "Kayitli Yukle" },
  "discounts.scanBtn": { en: "Scan New Vibes", tr: "Yeni Havaları Tara" },
  "discounts.scanning": { en: "Scanning local signals...", tr: "Yerel sinyaller taranıyor..." },
  "discounts.exploreBtn": { en: "Explore", tr: "Keşfet" },
  "discounts.quietTitle": { en: "Quiet world today!", tr: "Bugün buralar sessiz!" },
  "discounts.quietSubtitle": { en: "No specific vibes found in your signals. Check back soon!", tr: "Sinyallerinizde özel bir hava bulunamadı. Yakında tekrar kontrol edin!" },
  "discounts.tryRefresh": { en: "Try Refreshing", tr: "Yenilemeyi Dene" },
  "discounts.tryRefresh": { en: "Try Refreshing", tr: "Yenilemeyi Dene" },

  // ==========================================
  // TRAVEL PLANNER
  // ==========================================
  "travel.headerTitle": { en: "AI Travel Planner", tr: "AI Seyahat Planlayıcı" },
  "travel.headerSubtitle": { en: "Enter your dates, and let AI build your perfect itinerary.", tr: "Tarihlerinizi girin ve AI'nın size mükemmel gezi planınızı oluşturmasına izin verin." },
  "travel.fromLabel": { en: "From (City)", tr: "Nereden (Şehir)" },
  "travel.fromPlaceholder": { en: "e.g. London", tr: "ör. İstanbul" },
  "travel.toLabel": { en: "To (Destination)", tr: "Nereye (Hedef)" },
  "travel.toPlaceholder": { en: "e.g. Tokyo", tr: "ör. Tokyo" },
  "travel.dateLabel": { en: "Travel Date", tr: "Seyahat Tarihi" },
  "travel.generateBtn": { en: "Generate Itinerary 🚀", tr: "Gezi Planı Oluştur 🚀" },
  "travel.readyTitle": { en: "Ready to fly?", tr: "Uçmaya hazır mısın?" },
  "travel.readySubtitle": { en: "We found the search page for your specific dates.", tr: "Tarihleriniz için arama sayfasını bulduk." },
  "travel.checkFlightsBtn": { en: "Check Real-Time Flight Prices", tr: "Gerçek Zamanlı Uçak Fiyatlarını Kontrol Et" },
  "travel.topPlaces": { en: "Top Places to Visit", tr: "Gezilecek En İyi Yerler" },
  "travel.fillAllToast": { en: "Please fill in all fields!", tr: "Lütfen tüm alanları doldurun!" },
  "travel.successToast": { en: "Trip planned successfully! 🌍", tr: "Seyahat planı başarıyla oluşturuldu! 🌍" },
  "travel.failToast": { en: "Failed to generate plan. Try again.", tr: "Plan oluşturulamadı. Tekrar deneyin." },
  "cv.headerTitle": { en: "CV", tr: "CV" },
  "cv.headerSubtitle": { en: "Designer", tr: "Tasarımcı" },
  "cv.saving": { en: "Saving...", tr: "Kaydediliyor..." },
  "cv.perfect": { en: "Perfect", tr: "Mükemmel" },
  "cv.themes": { en: "Themes", tr: "Temalar" },
  "cv.coreContact": { en: "Core Contact", tr: "Ana İletişim" },
  "cv.phonePlaceholder": { en: "Phone Number", tr: "Telefon Numarası" },
  "cv.customLinks": { en: "Custom Links", tr: "Özel Bağlantılar" },
  "cv.addBtn": { en: "+ Add", tr: "+ Ekle" },
  "cv.theArsenal": { en: "The Arsenal", tr: "Cephanelik" },
  "cv.addJourneyBtn": { en: "Add Journey", tr: "Yolculuk Ekle" },
  "cv.workExp": { en: "Work Experience", tr: "İş Deneyimi" },
  "cv.education": { en: "Education", tr: "Eğitim" },
  "cv.languages": { en: "Languages", tr: "Diller" },
  "cv.customList": { en: "Custom List", tr: "Özel Liste" },
  "cv.customText": { en: "Custom Text", tr: "Özel Metin" },
  "cv.rolePlaceholder": { en: "Role", tr: "Rol" },
  "cv.companyPlaceholder": { en: "Company", tr: "Şirket" },
  "cv.fromPlaceholder": { en: "From", tr: "Başlangıç" },
  "cv.toPlaceholder": { en: "To (or Present)", tr: "Bitiş (veya Günümüz)" },
  "cv.descPlaceholder": { en: "Description", tr: "Açıklama" },
  "cv.degreePlaceholder": { en: "Degree", tr: "Derece" },
  "cv.schoolPlaceholder": { en: "School/Uni", tr: "Okul/Üni" },
  "cv.contentPlaceholder": { en: "Content", tr: "İçerik" },
  "cv.downloadBtn": { en: "Download Masterpiece", tr: "Başyapıtı İndir" },
  "cv.narrative": { en: "Narrative", tr: "Anlatı" },
  "cv.industryImpact": { en: "Industry Impact", tr: "Endüstri Etkisi" },
  "cv.academicGenesis": { en: "Academic Genesis", tr: "Akademik Geçmiş" },
  "cv.missionLog": { en: "Mission Log", tr: "Görev Günlüğü" },
  "cv.competencies": { en: "Competencies", tr: "Yetkinlikler" },
  "cv.passions": { en: "Passions", tr: "Tutkular" },
  "cv.years": { en: "Years", tr: "Yıl" },
  "cv.inProgress": { en: "In Progress", tr: "Devam Ediyor" },
  "cv.noMissions": { en: "No missions completed yet.", tr: "Henüz görev tamamlanmadı." },
  "cv.errorLoading": { en: "Error loading CV data! 🚀", tr: "CV verileri yüklenirken hata oluştu! 🚀" },
  "cv.generatingToast": { en: "Generating your Masterpiece PDF... ✨", tr: "Masterpiece PDF'iniz oluşturuluyor... ✨" },
  "cv.downloadedToast": { en: "Downloaded! 🚀", tr: "İndirildi! 🚀" },
  "cv.failToast": { en: "PDF generation failed.", tr: "PDF oluşturma başarısız." },

  // ==========================================
  // CAREER ROADMAP
  // ==========================================
  "career.title": { en: "Career", tr: "Kariyer" },
  "career.roadmap": { en: "Roadmap", tr: "Yol Haritası" },
  "career.subtitle": { en: "Your AI-generated career path.", tr: "AI tarafından oluşturulan kariyer yolunuz." },
  "career.generate": { en: "Generate Plan", tr: "Plan Oluştur" },

  // ==========================================
  // TODO LIST
  // ==========================================
  "todo.title": { en: "Mission Log", tr: "Görev Kaydı" },
  "todo.add": { en: "Add Task", tr: "Görev Ekle" },
  "todo.placeholder": { en: "What needs to be done?", tr: "Ne yapılması gerekiyor?" },
  "todo.urgent": { en: "Urgent", tr: "Acil" },
  "todo.completed": { en: "Completed", tr: "Tamamlandı" },
  "todo.delete": { en: "Delete", tr: "Sil" },

  // ==========================================
  // COMMON / SHARED
  // ==========================================
  "common.loading": { en: "Loading...", tr: "Yükleniyor..." },
  "common.error": { en: "Something went wrong.", tr: "Bir şeyler yanlış gitti." },
  "common.save": { en: "Save", tr: "Kaydet" },
  "common.cancel": { en: "Cancel", tr: "İptal" },
  "common.submit": { en: "Submit", tr: "Gönder" },
  "common.back": { en: "Back", tr: "Geri" },
  "common.next": { en: "Next", tr: "İleri" },
  "common.search": { en: "Search", tr: "Ara" },
  "common.noData": { en: "No data available.", tr: "Veri bulunamadı." },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("language") || "en"
  );

  const toggleLanguage = () => {
    const newLang = language === "en" ? "tr" : "en";
    setLanguage(newLang);
    localStorage.setItem("language", newLang);
  };

  const t = (key) => {
    const entry = translations[key];
    if (!entry) return key; // Fallback: show key if not found
    return entry[language] || entry["en"] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
